services:
  laravel-docker: 
    container_name: laravel-docker
    build: .
    volumes:
      - ./App:/var/www/html
    ports:
      - 9000:80
  
  mysql_db:
    image: mysql:latest # Put Specific version
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_docker
    ports:
      - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin:latest # Put Specific Version
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
